---
- name: Ensure ironic inspector kernel and ramdisk images are present
  vars:
    image_download_url: "{{ item.url }}"
    image_download_checksum_url: "{{ item.checksum_url }}"
    image_download_checksum_algorithm: "{{ item.checksum_algorithm }}"
    image_download_path: "{{ item.path }}"
    image_download_dest: "{{ item.dest }}"
  include_role:
    name: image-download
  with_items:
    - url: "{{ kolla_inspector_ipa_kernel_upstream_url }}"
      checksum_url: "{{ kolla_inspector_ipa_kernel_checksum_url }}"
      checksum_algorithm: "{{ kolla_inspector_ipa_kernel_checksum_algorithm }}"
      path: "{{ kolla_inspector_ipa_kernel_path }}"
      dest: "{{ kolla_node_custom_config_path }}/ironic/ironic-agent.kernel"
    - url: "{{ kolla_inspector_ipa_ramdisk_upstream_url }}"
      checksum_url: "{{ kolla_inspector_ipa_ramdisk_checksum_url }}"
      checksum_algorithm: "{{ kolla_inspector_ipa_ramdisk_checksum_algorithm }}"
      path: "{{ kolla_inspector_ipa_ramdisk_path }}"
      dest: "{{ kolla_node_custom_config_path }}/ironic/ironic-agent.initramfs"
  when: kolla_enable_ironic | bool
  loop_control:
    label: "{{ item.dest }}"

# We support a fairly flexible mechanism of dropping config file templates into
# an 'extra' config directory, and passing these through to kolla-ansible. We
# look for matching files in the source directory to template, and also remove
# any unexpected files from the destination, to support removal of files.

- name: Collect details about custom config
  kolla_custom_config_info:
    destination: "{{ kolla_node_custom_config_path }}"
    ignore_globs: "{{ _kolla_openstack_custom_config_cleanup_ignore_globs }}"
    include_globs: "{{ kolla_openstack_custom_config_include_globs }}"
    merge_ini_globs: "{{ kolla_openstack_custom_config_merge_ini_globs }}"
    merge_yml_globs: "{{ kolla_openstack_custom_config_merge_yml_globs }}"
    search_paths: "{{ kolla_extra_config_paths }}"
    template_exclude_globs: "{{ kolla_openstack_custom_config_template_exclude_globs }}"
  register: kolla_custom_config_info

- name: Print kolla_custom_config_info when using -v
  debug:
    msg: "{{ kolla_custom_config_info }}"
    verbosity: 1

- name: Ensure extra configuration parent directories are present
  file:
    path: "{{ item }}"
    recurse: true
    state: directory
  with_items: "{{ kolla_custom_config_info.create_dir }}"

- name: Ensure templated extra configuration files exist
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0640
  with_items: "{{ kolla_custom_config_info.template }}"

- name: Ensure untemplated extra configuration files exist
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0640
  # NOTE: .copy is ambiguous with copy method
  with_items: "{{ kolla_custom_config_info['copy'] }}"

- name: Ensure merged ini extra configuration files exist
  merge_configs:
    sources: "{{ item.sources }}"
    dest: "{{ item.dest }}"
    mode: 0640
  with_items: "{{ kolla_custom_config_info.merge_ini }}"

- name: Ensure merged yaml extra configuration files exist
  merge_yaml:
    sources: "{{ item.sources }}"
    dest: "{{ item.dest }}"
    mode: 0640
  with_items: "{{ kolla_custom_config_info.merge_yaml }}"

- name: Ensure unnecessary extra configuration files are absent
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ kolla_custom_config_info.delete }}"
