---

# An internal variable used for cleaning files from the generated config
# directory. Should not be exposed as we may wish to change the cleanup
# mechanism to something more robust.
_kolla_openstack_custom_config_cleanup_ignore_globs:
  - ironic/ironic-agent.initramfs
  - ironic/ironic-agent.kernel
  - neutron/ml2_conf.ini
