---
- name: Ensure timezone is configured
  hosts: seed-hypervisor:seed:overcloud
  tags:
    - timezone
  tasks:
    - import_role:
        name: yatesr.timezone
      become: True

- name: Ensure Chrony is installed and configured
  hosts: ntp
  tags:
    - ntp
  tasks:
    - import_role:
        name: ntp
      when: not kolla_enable_chrony | bool
